services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend.dockerfile
      args:
        MODE: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/nginx.local.conf:/etc/nginx/conf.d/frontend.conf:ro
    networks:
      - app-network
    depends_on:
      - users
      - ping
      - proxy

  proxy:
    build:
      context: .
      dockerfile: ./proxy.dockerfile
      args:
          SERVICE_PATH: apis/proxy
          SRC_PATH: thoughtgears/cloud-run-multi-container-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./proxy/nginx.local.conf:/etc/nginx/conf.d/proxy.conf:ro
    networks:
    - app-network

  users:
    build:
      context: .
      dockerfile: ./users.dockerfile
      args:
        SERVICE_PATH: apis/users
        SRC_PATH: thoughtgears/cloud-run-multi-container-nginx
    networks:
      - app-network

  ping:
    build:
      context: .
      dockerfile: ./ping.dockerfile
      args:
        SERVICE_PATH: apis/ping
        SRC_PATH: thoughtgears/cloud-run-multi-container-nginx
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /config/application_default_credentials.json
      FIREBASE_PROJECT_ID: ${GCP_PROJECT_ID}
    ports:
      - "8081:8080"
    volumes:
      - ~/.config/gcloud:/config:ro
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
