version: 3

dotenv: [ '.env', '{{.ENV}}/.env.', '{{.HOME}}/.env' ]

# Dynamic variables for the task runners
vars:
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  GIT_REPO:
    sh: git config --get remote.origin.url | sed -e 's#^.*:##' -e 's#.git$##' -e 's#//github.com/*##'
  GIT_REPO_NAME:
    sh: echo {{.GIT_REPO}} | sed -e 's#^.*/##'
  GIT_OWNER:
    sh: echo {{.GIT_REPO}} | sed -e 's#/.*$##'
  DOCKER_REPO: 'echo ${DOCKER_REPO}'


tasks:
  default:
    cmds:
      - task --list

  build:apis:ping:
    desc: Build the ping API
    vars:
      SERVICE_NAME: ping
    cmds:
      - docker build --platform linux/amd64 --build-arg SERVICE_PATH=apis/ping  --build-arg SRC_PATH={{ .GIT_REPO }} -f ping.dockerfile -t {{.DOCKER_REPO }}/{{ .SERVICE_NAME }}:latest .
      - docker tag {{.DOCKER_REPO}}/{{ .SERVICE_NAME }}:latest {{.DOCKER_REPO}}/{{ .SERVICE_NAME }}:{{.GIT_COMMIT}}
      - docker push {{.DOCKER_REPO}}/{{ .SERVICE_NAME }}:latest
      - docker push {{.DOCKER_REPO}}/{{ .SERVICE_NAME }}:{{.GIT_COMMIT}}

  build:apis:users:
    desc: Build the users API
    vars:
      SERVICE_NAME: users
    cmds:
      - docker build --platform linux/amd64 --build-arg SERVICE_PATH=apis/users  --build-arg SRC_PATH={{ .GIT_REPO }} -f users.dockerfile -t {{.DOCKER_REPO }}/{{ .SERVICE_NAME }}:latest .
      - docker tag {{.DOCKER_REPO}}/{{ .SERVICE_NAME }}:latest {{.DOCKER_REPO}}/{{ .SERVICE_NAME }}:{{.GIT_COMMIT}}
      - docker push {{.DOCKER_REPO}}/{{ .SERVICE_NAME }}:latest
      - docker push {{.DOCKER_REPO}}/{{ .SERVICE_NAME }}:{{.GIT_COMMIT}}

  build:proxy:
    desc: Build the API proxy
    vars:
      SERVICE_NAME: proxy
    cmds:
      - docker build --platform linux/amd64 -f proxy.dockerfile -t {{.DOCKER_REPO }}/{{ .SERVICE_NAME }}:latest .
      - docker tag {{.DOCKER_REPO}}/{{ .SERVICE_NAME }}:latest {{.DOCKER_REPO}}/{{ .SERVICE_NAME }}:{{.GIT_COMMIT}}
      - docker push {{.DOCKER_REPO}}/{{ .SERVICE_NAME }}:latest
      - docker push {{.DOCKER_REPO}}/{{ .SERVICE_NAME }}:{{.GIT_COMMIT}}

  build:all:
    desc: Build all APIs
    cmds:
      - task build:apis:ping
      - task build:apis:users
      - task build:proxy